apiVersion: v1
kind: ServiceAccount
metadata:
  name: edns-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edns-operator
spec:
  selector:
    matchLabels:
      app: edns-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: edns-operator
    spec:
      serviceAccountName: edns-operator
      containers:
        - name: operator
          image: ghcr.io/ellipticconsulting/edns-operator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: awscred
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: awscred
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: "100m"
              memory: 256Mi
            limits:
              cpu: "500m"
              memory: 512Mi
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /startup
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 2
            failureThreshold: 3
