---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-admin
subjects:
  - kind: ServiceAccount
    name: edns-operator
    namespace: edns-operator
roleRef:
  kind: ClusterRole
  name: edns-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edns-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - "apps"
    resources:
      - services
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "elliptic.external.dns"
    resources:
      - externaldnses
      - externaldnses/status
    verbs:
      - '*'
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - '*'
